sudo: false
language: node_js
node_js:
  - "node"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
branches:
  only:
    - master

# install peer dependencies before running test
before_script: "npm install $(node ./scripts/extraDependencies.js"

# coveralls on success
after_success: "npm run coverage"
